var archi1 = document.querySelector('#archi1');
var archi2 = document.querySelector('#archi2');
var archi3 = document.querySelector('#archi3');
var archi4 = document.querySelector('#archi4');
var archi5 = document.querySelector('#archi5');
var archi6 = document.querySelector('#archi6');
var archi7 = document.querySelector('#archi7');
var archi8 = document.querySelector('#archi8');
var archi9 = document.querySelector('#archi9');
var archi10 = document.querySelector('#archi10');
var archi11 = document.querySelector('#archi11');
var archi12 = document.querySelector('#archi12');
var archi13 = document.querySelector('#archi13');
var archi14 = document.querySelector('#archi14');
var archi15 = document.querySelector('#archi15');
var archi16 = document.querySelector('#archi16');
var archi17 = document.querySelector('#archi17');
var archi18 = document.querySelector('#archi18');
var archi19 = document.querySelector('#archi19');
var archi20 = document.querySelector('#archi20');
var archi21 = document.querySelector('#archi21');
var archi22 = document.querySelector('#archi22');
var archi23 = document.querySelector('#archi23');
var archi24 = document.querySelector('#archi24');
var archi25 = document.querySelector('#archi25');
var archi26 = document.querySelector('#archi26');
var archi27 = document.querySelector('#archi27');
var archi28 = document.querySelector('#archi28');
var archi29 = document.querySelector('#archi29');
var archi20 = document.querySelector('#archi30');
var archi31 = document.querySelector('#archi31');
var archi32 = document.querySelector('#archi32');
var archi33 = document.querySelector('#archi33');
var archi34 = document.querySelector('#archi34');
var archi35 = document.querySelector('#archi35');
var archi36 = document.querySelector('#archi36');
var archi37 = document.querySelector('#archi37');
var archi38 = document.querySelector('#archi38');
var archi39 = document.querySelector('#archi39');
var archi40 = document.querySelector('#archi40');
var archi41 = document.querySelector('#archi41');
var archi42 = document.querySelector('#archi42');
var archi43 = document.querySelector('#archi43');
var archi44 = document.querySelector('#archi44');
var archi45 = document.querySelector('#archi45');
var archi46 = document.querySelector('#archi46');
var archi47 = document.querySelector('#archi47');
var archi48 = document.querySelector('#archi48');
var archi49 = document.querySelector('#archi49');
var archi50 = document.querySelector('#archi50');
var archi51 = document.querySelector('#archi51');
var archi52 = document.querySelector('#archi52');
var archi53 = document.querySelector('#archi53');
var archi54 = document.querySelector('#archi54');
var archi55 = document.querySelector('#archi55');
var archi56 = document.querySelector('#archi56');
var archi57 = document.querySelector('#archi57');
var archi58 = document.querySelector('#archi58');
var archi59 = document.querySelector('#archi59');
var archi60 = document.querySelector('#archi60');
var archi61 = document.querySelector('#archi61');
var archi62 = document.querySelector('#archi62');
var archi63 = document.querySelector('#archi63');
var archi64 = document.querySelector('#archi64');
var archi65 = document.querySelector('#archi65');
var archi66 = document.querySelector('#archi66');
var archi67 = document.querySelector('#archi67');
var archi68 = document.querySelector('#archi68');
var archi69 = document.querySelector('#archi69');
var archi70 = document.querySelector('#archi70');
var archi71 = document.querySelector('#archi71');
var archi72 = document.querySelector('#archi72');
var archi73 = document.querySelector('#archi73');
var archi74 = document.querySelector('#archi74');
var archi75 = document.querySelector('#archi75');
var archi76 = document.querySelector('#archi76');
var archi77 = document.querySelector('#archi77');
var archi78 = document.querySelector('#archi78');
var archi79 = document.querySelector('#archi79');
var archi80 = document.querySelector('#archi80');
var archi81 = document.querySelector('#archi81');
var archi82 = document.querySelector('#archi82');
var archi83 = document.querySelector('#archi83');
var archi84 = document.querySelector('#archi84');
var archi85 = document.querySelector('#archi85');
var archi86 = document.querySelector('#archi86');
var archi87 = document.querySelector('#archi87');
var archi88 = document.querySelector('#archi88');
var archi89 = document.querySelector('#archi89');
var archi90 = document.querySelector('#archi90');
var archi91 = document.querySelector('#archi91');
var archi92 = document.querySelector('#archi92');
var archi93 = document.querySelector('#archi93');
var archi94 = document.querySelector('#archi94');
var archi95 = document.querySelector('#archi95');
var archi96 = document.querySelector('#archi96');
var archi97 = document.querySelector('#archi97');
var archi98 = document.querySelector('#archi98');
var archi99 = document.querySelector('#archi99');
var archi100 = document.querySelector('#archi100');
var archi101 = document.querySelector('#archi101');
var archi102 = document.querySelector('#archi102');
var archi103 = document.querySelector('#archi103');
var archi104 = document.querySelector('#archi104');
var archi105 = document.querySelector('#archi105');
var archi106 = document.querySelector('#archi106');
var archi107 = document.querySelector('#archi107');
var archi108 = document.querySelector('#archi108');
var archi109 = document.querySelector('#archi109');
var archi110 = document.querySelector('#archi110');
var archi111 = document.querySelector('#archi111');
var archi112 = document.querySelector('#archi112');
var archi113 = document.querySelector('#archi113');
var archi114 = document.querySelector('#archi114');
var archi115 = document.querySelector('#archi115');
var archi116 = document.querySelector('#archi116');
var archi117 = document.querySelector('#archi117');
var archi118 = document.querySelector('#archi118');
var archi119 = document.querySelector('#archi119');
var archi120 = document.querySelector('#archi120');
var archi121 = document.querySelector('#archi121');
var archi122 = document.querySelector('#archi122');
var archi123 = document.querySelector('#archi123');
var archi124 = document.querySelector('#archi124');
var archi125 = document.querySelector('#archi125');
var archi126 = document.querySelector('#archi126');
var archi127 = document.querySelector('#archi127');
var archi128 = document.querySelector('#archi128');
var archi129 = document.querySelector('#archi129');
var archi120 = document.querySelector('#archi130');
var archi131 = document.querySelector('#archi131');
var archi132 = document.querySelector('#archi132');
var archi133 = document.querySelector('#archi133');
var archi134 = document.querySelector('#archi134');
var archi135 = document.querySelector('#archi135');
var archi136 = document.querySelector('#archi136');
var archi137 = document.querySelector('#archi137');
var archi138 = document.querySelector('#archi138');
var archi139 = document.querySelector('#archi139');
var archi140 = document.querySelector('#archi140');
var archi141 = document.querySelector('#archi141');
var archi142 = document.querySelector('#archi142');
var archi143 = document.querySelector('#archi143');
var archi144 = document.querySelector('#archi144');
var archi145 = document.querySelector('#archi145');
var archi146 = document.querySelector('#archi146');
var archi147 = document.querySelector('#archi147');
var archi148 = document.querySelector('#archi148');
var archi149 = document.querySelector('#archi149');
var archi150 = document.querySelector('#archi150');
var archi151 = document.querySelector('#archi151');
var archi152 = document.querySelector('#archi152');
var archi153 = document.querySelector('#archi153');
var archi154 = document.querySelector('#archi154');
var archi155 = document.querySelector('#archi155');
var archi156 = document.querySelector('#archi156');
var archi157 = document.querySelector('#archi157');
var archi158 = document.querySelector('#archi158');
var archi159 = document.querySelector('#archi159');
var archi160 = document.querySelector('#archi160');
var archi161 = document.querySelector('#archi161');
var archi162 = document.querySelector('#archi162');
var archi163 = document.querySelector('#archi163');
var archi164 = document.querySelector('#archi164');
var archi165 = document.querySelector('#archi165');
var archi166 = document.querySelector('#archi166');
var archi167 = document.querySelector('#archi167');
var archi168 = document.querySelector('#archi168');
var archi169 = document.querySelector('#archi169');
var archi170 = document.querySelector('#archi170');
var archi171 = document.querySelector('#archi171');
var archi172 = document.querySelector('#archi172');
var archi173 = document.querySelector('#archi173');
var archi174 = document.querySelector('#archi174');
var archi175 = document.querySelector('#archi175');
var archi176 = document.querySelector('#archi176');
var archi177 = document.querySelector('#archi177');
var archi178 = document.querySelector('#archi178');
var archi179 = document.querySelector('#archi179');
var archi180 = document.querySelector('#archi180');
var archi181 = document.querySelector('#archi181');
var archi182 = document.querySelector('#archi182');
var archi183 = document.querySelector('#archi183');
var archi184 = document.querySelector('#archi184');
var archi185 = document.querySelector('#archi185');
var archi186 = document.querySelector('#archi186');
var archi187 = document.querySelector('#archi187');
var archi188 = document.querySelector('#archi188');
var archi189 = document.querySelector('#archi189');
var archi190 = document.querySelector('#archi190');
var archi191 = document.querySelector('#archi191');
var archi192 = document.querySelector('#archi192');
var archi193 = document.querySelector('#archi193');
var archi194 = document.querySelector('#archi194');
var archi195 = document.querySelector('#archi195');
var archi196 = document.querySelector('#archi196');
var archi197 = document.querySelector('#archi197');
var archi198 = document.querySelector('#archi198');
var archi199 = document.querySelector('#archi199');
var archi200 = document.querySelector('#archi200');

var animar = 0;
var animaratt = 0;
var abcanims = 0;
var material = document.createAttribute('material');


function startanim() {
    material.value = 'src: bola.mp4';
    animar.setAttributeNode(material);
}

















/*
archi1.addEventListener('animationend',function () {endanim();});
archi2.addEventListener('animationend',function () {endanim();});
archi3.addEventListener('animationend',function () {endanim();});
archi4.addEventListener('animationend',function () {endanim();});
archi5.addEventListener('animationend',function () {endanim();});
archi6.addEventListener('animationend',function () {endanim();});
archi7.addEventListener('animationend',function () {endanim();});
archi8.addEventListener('animationend',function () {endanim();});
archi9.addEventListener('animationend',function () {endanim();});
archi10.addEventListener('animationend',function () {endanim();});
archi11.addEventListener('animationend',function () {endanim();});
archi12.addEventListener('animationend',function () {endanim();});
archi13.addEventListener('animationend',function () {endanim();});
archi14.addEventListener('animationend',function () {endanim();});
archi15.addEventListener('animationend',function () {endanim();});
archi16.addEventListener('animationend',function () {endanim();});
archi17.addEventListener('animationend',function () {endanim();});
archi18.addEventListener('animationend',function () {endanim();});
archi19.addEventListener('animationend',function () {endanim();});
archi20.addEventListener('animationend',function () {endanim();});
archi21.addEventListener('animationend',function () {endanim();});
archi22.addEventListener('animationend',function () {endanim();});
archi23.addEventListener('animationend',function () {endanim();});
archi24.addEventListener('animationend',function () {endanim();});
archi25.addEventListener('animationend',function () {endanim();});
archi26.addEventListener('animationend',function () {endanim();});
archi27.addEventListener('animationend',function () {endanim();});
archi28.addEventListener('animationend',function () {endanim();});
archi29.addEventListener('animationend',function () {endanim();});
archi30.addEventListener('animationend',function () {endanim();});
archi31.addEventListener('animationend',function () {endanim();});
archi32.addEventListener('animationend',function () {endanim();});
archi33.addEventListener('animationend',function () {endanim();});
archi34.addEventListener('animationend',function () {endanim();});
archi35.addEventListener('animationend',function () {endanim();});
archi36.addEventListener('animationend',function () {endanim();});
archi37.addEventListener('animationend',function () {endanim();});
archi38.addEventListener('animationend',function () {endanim();});
archi39.addEventListener('animationend',function () {endanim();});
archi40.addEventListener('animationend',function () {endanim();});
archi41.addEventListener('animationend',function () {endanim();});
archi42.addEventListener('animationend',function () {endanim();});
archi43.addEventListener('animationend',function () {endanim();});
archi44.addEventListener('animationend',function () {endanim();});
archi45.addEventListener('animationend',function () {endanim();});
archi46.addEventListener('animationend',function () {endanim();});
archi47.addEventListener('animationend',function () {endanim();});
archi48.addEventListener('animationend',function () {endanim();});
archi49.addEventListener('animationend',function () {endanim();});
archi50.addEventListener('animationend',function () {endanim();});
archi51.addEventListener('animationend',function () {endanim();});
archi52.addEventListener('animationend',function () {endanim();});
archi53.addEventListener('animationend',function () {endanim();});
archi54.addEventListener('animationend',function () {endanim();});
archi55.addEventListener('animationend',function () {endanim();});
archi56.addEventListener('animationend',function () {endanim();});
archi57.addEventListener('animationend',function () {endanim();});
archi58.addEventListener('animationend',function () {endanim();});
archi59.addEventListener('animationend',function () {endanim();});
archi60.addEventListener('animationend',function () {endanim();});
archi61.addEventListener('animationend',function () {endanim();});
archi62.addEventListener('animationend',function () {endanim();});
archi63.addEventListener('animationend',function () {endanim();});
archi64.addEventListener('animationend',function () {endanim();});
archi65.addEventListener('animationend',function () {endanim();});
archi66.addEventListener('animationend',function () {endanim();});
archi67.addEventListener('animationend',function () {endanim();});
archi68.addEventListener('animationend',function () {endanim();});
archi69.addEventListener('animationend',function () {endanim();});
archi70.addEventListener('animationend',function () {endanim();});
archi71.addEventListener('animationend',function () {endanim();});
archi72.addEventListener('animationend',function () {endanim();});
archi73.addEventListener('animationend',function () {endanim();});
archi74.addEventListener('animationend',function () {endanim();});
archi75.addEventListener('animationend',function () {endanim();});
archi76.addEventListener('animationend',function () {endanim();});
archi77.addEventListener('animationend',function () {endanim();});
archi78.addEventListener('animationend',function () {endanim();});
archi79.addEventListener('animationend',function () {endanim();});
archi80.addEventListener('animationend',function () {endanim();});
archi81.addEventListener('animationend',function () {endanim();});
archi82.addEventListener('animationend',function () {endanim();});
archi83.addEventListener('animationend',function () {endanim();});
archi84.addEventListener('animationend',function () {endanim();});
archi85.addEventListener('animationend',function () {endanim();});
archi86.addEventListener('animationend',function () {endanim();});
archi87.addEventListener('animationend',function () {endanim();});
archi88.addEventListener('animationend',function () {endanim();});
archi89.addEventListener('animationend',function () {endanim();});
archi90.addEventListener('animationend',function () {endanim();});
archi91.addEventListener('animationend',function () {endanim();});
archi92.addEventListener('animationend',function () {endanim();});
archi93.addEventListener('animationend',function () {endanim();});
archi94.addEventListener('animationend',function () {endanim();});
archi95.addEventListener('animationend',function () {endanim();});
archi96.addEventListener('animationend',function () {endanim();});
archi97.addEventListener('animationend',function () {endanim();});
archi98.addEventListener('animationend',function () {endanim();});
archi99.addEventListener('animationend',function () {endanim();});
archi100.addEventListener('animationend',function () {endanim();});
archi101.addEventListener('animationend',function () {endanim();});
archi102.addEventListener('animationend',function () {endanim();});
archi103.addEventListener('animationend',function () {endanim();});
archi104.addEventListener('animationend',function () {endanim();});
archi105.addEventListener('animationend',function () {endanim();});
archi106.addEventListener('animationend',function () {endanim();});
archi107.addEventListener('animationend',function () {endanim();});
archi108.addEventListener('animationend',function () {endanim();});
archi109.addEventListener('animationend',function () {endanim();});
archi110.addEventListener('animationend',function () {endanim();});
archi111.addEventListener('animationend',function () {endanim();});
archi112.addEventListener('animationend',function () {endanim();});
archi113.addEventListener('animationend',function () {endanim();});
archi114.addEventListener('animationend',function () {endanim();});
archi115.addEventListener('animationend',function () {endanim();});
archi116.addEventListener('animationend',function () {endanim();});
archi117.addEventListener('animationend',function () {endanim();});
archi118.addEventListener('animationend',function () {endanim();});
archi119.addEventListener('animationend',function () {endanim();});
archi120.addEventListener('animationend',function () {endanim();});
archi121.addEventListener('animationend',function () {endanim();});
archi122.addEventListener('animationend',function () {endanim();});
archi123.addEventListener('animationend',function () {endanim();});
archi124.addEventListener('animationend',function () {endanim();});
archi125.addEventListener('animationend',function () {endanim();});
archi126.addEventListener('animationend',function () {endanim();});
archi127.addEventListener('animationend',function () {endanim();});
archi128.addEventListener('animationend',function () {endanim();});
archi129.addEventListener('animationend',function () {endanim();});
archi130.addEventListener('animationend',function () {endanim();});
archi131.addEventListener('animationend',function () {endanim();});
archi132.addEventListener('animationend',function () {endanim();});
archi133.addEventListener('animationend',function () {endanim();});
archi134.addEventListener('animationend',function () {endanim();});
archi135.addEventListener('animationend',function () {endanim();});
archi136.addEventListener('animationend',function () {endanim();});
archi137.addEventListener('animationend',function () {endanim();});
archi138.addEventListener('animationend',function () {endanim();});
archi139.addEventListener('animationend',function () {endanim();});
archi140.addEventListener('animationend',function () {endanim();});
archi141.addEventListener('animationend',function () {endanim();});
archi142.addEventListener('animationend',function () {endanim();});
archi143.addEventListener('animationend',function () {endanim();});
archi144.addEventListener('animationend',function () {endanim();});
archi145.addEventListener('animationend',function () {endanim();});
archi146.addEventListener('animationend',function () {endanim();});
archi147.addEventListener('animationend',function () {endanim();});
archi148.addEventListener('animationend',function () {endanim();});
archi149.addEventListener('animationend',function () {endanim();});
archi150.addEventListener('animationend',function () {endanim();});
archi151.addEventListener('animationend',function () {endanim();});
archi152.addEventListener('animationend',function () {endanim();});
archi153.addEventListener('animationend',function () {endanim();});
archi154.addEventListener('animationend',function () {endanim();});
archi155.addEventListener('animationend',function () {endanim();});
archi156.addEventListener('animationend',function () {endanim();});
archi157.addEventListener('animationend',function () {endanim();});
archi158.addEventListener('animationend',function () {endanim();});
archi159.addEventListener('animationend',function () {endanim();});
archi160.addEventListener('animationend',function () {endanim();});
archi161.addEventListener('animationend',function () {endanim();});
archi162.addEventListener('animationend',function () {endanim();});
archi163.addEventListener('animationend',function () {endanim();});
archi164.addEventListener('animationend',function () {endanim();});
archi165.addEventListener('animationend',function () {endanim();});
archi166.addEventListener('animationend',function () {endanim();});
archi167.addEventListener('animationend',function () {endanim();});
archi168.addEventListener('animationend',function () {endanim();});
archi169.addEventListener('animationend',function () {endanim();});
archi170.addEventListener('animationend',function () {endanim();});
archi171.addEventListener('animationend',function () {endanim();});
archi172.addEventListener('animationend',function () {endanim();});
archi173.addEventListener('animationend',function () {endanim();});
archi174.addEventListener('animationend',function () {endanim();});
archi175.addEventListener('animationend',function () {endanim();});
archi176.addEventListener('animationend',function () {endanim();});
archi177.addEventListener('animationend',function () {endanim();});
archi178.addEventListener('animationend',function () {endanim();});
archi179.addEventListener('animationend',function () {endanim();});
archi180.addEventListener('animationend',function () {endanim();});
archi181.addEventListener('animationend',function () {endanim();});
archi182.addEventListener('animationend',function () {endanim();});
archi183.addEventListener('animationend',function () {endanim();});
archi184.addEventListener('animationend',function () {endanim();});
archi185.addEventListener('animationend',function () {endanim();});
archi186.addEventListener('animationend',function () {endanim();});
archi187.addEventListener('animationend',function () {endanim();});
archi188.addEventListener('animationend',function () {endanim();});
archi189.addEventListener('animationend',function () {endanim();});
archi190.addEventListener('animationend',function () {endanim();});
archi191.addEventListener('animationend',function () {endanim();});
archi192.addEventListener('animationend',function () {endanim();});
archi193.addEventListener('animationend',function () {endanim();});
archi194.addEventListener('animationend',function () {endanim();});
archi195.addEventListener('animationend',function () {endanim();});
archi196.addEventListener('animationend',function () {endanim();});
archi197.addEventListener('animationend',function () {endanim();});
archi198.addEventListener('animationend',function () {endanim();});
archi199.addEventListener('animationend',function () {endanim();});
archi200.addEventListener('animationend',function () {endanim();});
*/






















archi1.addEventListener('animationstart',function () {animar=archi1;startanim();});
archi2.addEventListener('animationstart',function () {animar=archi2;startanim();});
archi3.addEventListener('animationstart',function () {animar=archi3;startanim();});
archi4.addEventListener('animationstart',function () {animar=archi4;startanim();});
archi5.addEventListener('animationstart',function () {animar=archi5;startanim();});
archi6.addEventListener('animationstart',function () {animar=archi6;startanim();});
archi7.addEventListener('animationstart',function () {animar=archi7;startanim();});
archi8.addEventListener('animationstart',function () {animar=archi8;startanim();});
archi9.addEventListener('animationstart',function () {animar=archi9;startanim();});
archi10.addEventListener('animationstart',function () {animar=archi10;startanim();});
archi11.addEventListener('animationstart',function () {animar=archi11;startanim();});
archi12.addEventListener('animationstart',function () {animar=archi12;startanim();});
archi13.addEventListener('animationstart',function () {animar=archi13;startanim();});
archi14.addEventListener('animationstart',function () {animar=archi14;startanim();});
archi15.addEventListener('animationstart',function () {animar=archi15;startanim();});
archi16.addEventListener('animationstart',function () {animar=archi16;startanim();});
archi17.addEventListener('animationstart',function () {animar=archi17;startanim();});
archi18.addEventListener('animationstart',function () {animar=archi18;startanim();});
archi19.addEventListener('animationstart',function () {animar=archi19;startanim();});
archi20.addEventListener('animationstart',function () {animar=archi20;startanim();});
archi21.addEventListener('animationstart',function () {animar=archi21;startanim();});
archi22.addEventListener('animationstart',function () {animar=archi22;startanim();});
archi23.addEventListener('animationstart',function () {animar=archi23;startanim();});
archi24.addEventListener('animationstart',function () {animar=archi24;startanim();});
archi25.addEventListener('animationstart',function () {animar=archi25;startanim();});
archi26.addEventListener('animationstart',function () {animar=archi26;startanim();});
archi27.addEventListener('animationstart',function () {animar=archi27;startanim();});
archi28.addEventListener('animationstart',function () {animar=archi28;startanim();});
archi29.addEventListener('animationstart',function () {animar=archi29;startanim();});
archi30.addEventListener('animationstart',function () {animar=archi30;startanim();});
archi31.addEventListener('animationstart',function () {animar=archi31;startanim();});
archi32.addEventListener('animationstart',function () {animar=archi32;startanim();});
archi33.addEventListener('animationstart',function () {animar=archi33;startanim();});
archi34.addEventListener('animationstart',function () {animar=archi34;startanim();});
archi35.addEventListener('animationstart',function () {animar=archi35;startanim();});
archi36.addEventListener('animationstart',function () {animar=archi36;startanim();});
archi37.addEventListener('animationstart',function () {animar=archi37;startanim();});
archi38.addEventListener('animationstart',function () {animar=archi38;startanim();});
archi39.addEventListener('animationstart',function () {animar=archi39;startanim();});
archi40.addEventListener('animationstart',function () {animar=archi40;startanim();});
archi41.addEventListener('animationstart',function () {animar=archi41;startanim();});
archi42.addEventListener('animationstart',function () {animar=archi42;startanim();});
archi43.addEventListener('animationstart',function () {animar=archi43;startanim();});
archi44.addEventListener('animationstart',function () {animar=archi44;startanim();});
archi45.addEventListener('animationstart',function () {animar=archi45;startanim();});
archi46.addEventListener('animationstart',function () {animar=archi46;startanim();});
archi47.addEventListener('animationstart',function () {animar=archi47;startanim();});
archi48.addEventListener('animationstart',function () {animar=archi48;startanim();});
archi49.addEventListener('animationstart',function () {animar=archi49;startanim();});
archi50.addEventListener('animationstart',function () {animar=archi50;startanim();});
archi51.addEventListener('animationstart',function () {animar=archi51;startanim();});
archi52.addEventListener('animationstart',function () {animar=archi52;startanim();});
archi53.addEventListener('animationstart',function () {animar=archi53;startanim();});
archi54.addEventListener('animationstart',function () {animar=archi54;startanim();});
archi55.addEventListener('animationstart',function () {animar=archi55;startanim();});
archi56.addEventListener('animationstart',function () {animar=archi56;startanim();});
archi57.addEventListener('animationstart',function () {animar=archi57;startanim();});
archi58.addEventListener('animationstart',function () {animar=archi58;startanim();});
archi59.addEventListener('animationstart',function () {animar=archi59;startanim();});
archi60.addEventListener('animationstart',function () {animar=archi60;startanim();});
archi61.addEventListener('animationstart',function () {animar=archi61;startanim();});
archi62.addEventListener('animationstart',function () {animar=archi62;startanim();});
archi63.addEventListener('animationstart',function () {animar=archi63;startanim();});
archi64.addEventListener('animationstart',function () {animar=archi64;startanim();});
archi65.addEventListener('animationstart',function () {animar=archi65;startanim();});
archi66.addEventListener('animationstart',function () {animar=archi66;startanim();});
archi67.addEventListener('animationstart',function () {animar=archi67;startanim();});
archi68.addEventListener('animationstart',function () {animar=archi68;startanim();});
archi69.addEventListener('animationstart',function () {animar=archi69;startanim();});
archi70.addEventListener('animationstart',function () {animar=archi70;startanim();});
archi71.addEventListener('animationstart',function () {animar=archi71;startanim();});
archi72.addEventListener('animationstart',function () {animar=archi72;startanim();});
archi73.addEventListener('animationstart',function () {animar=archi73;startanim();});
archi74.addEventListener('animationstart',function () {animar=archi74;startanim();});
archi75.addEventListener('animationstart',function () {animar=archi75;startanim();});
archi76.addEventListener('animationstart',function () {animar=archi76;startanim();});
archi77.addEventListener('animationstart',function () {animar=archi77;startanim();});
archi78.addEventListener('animationstart',function () {animar=archi78;startanim();});
archi79.addEventListener('animationstart',function () {animar=archi79;startanim();});
archi80.addEventListener('animationstart',function () {animar=archi80;startanim();});
archi81.addEventListener('animationstart',function () {animar=archi81;startanim();});
archi82.addEventListener('animationstart',function () {animar=archi82;startanim();});
archi83.addEventListener('animationstart',function () {animar=archi83;startanim();});
archi84.addEventListener('animationstart',function () {animar=archi84;startanim();});
archi85.addEventListener('animationstart',function () {animar=archi85;startanim();});
archi86.addEventListener('animationstart',function () {animar=archi86;startanim();});
archi87.addEventListener('animationstart',function () {animar=archi87;startanim();});
archi88.addEventListener('animationstart',function () {animar=archi88;startanim();});
archi89.addEventListener('animationstart',function () {animar=archi89;startanim();});
archi90.addEventListener('animationstart',function () {animar=archi90;startanim();});
archi91.addEventListener('animationstart',function () {animar=archi91;startanim();});
archi92.addEventListener('animationstart',function () {animar=archi92;startanim();});
archi93.addEventListener('animationstart',function () {animar=archi93;startanim();});
archi94.addEventListener('animationstart',function () {animar=archi94;startanim();});
archi95.addEventListener('animationstart',function () {animar=archi95;startanim();});
archi96.addEventListener('animationstart',function () {animar=archi96;startanim();});
archi97.addEventListener('animationstart',function () {animar=archi97;startanim();});
archi98.addEventListener('animationstart',function () {animar=archi98;startanim();});
archi99.addEventListener('animationstart',function () {animar=archi99;startanim();});
archi100.addEventListener('animationstart',function () {animar=archi100;startanim();});
archi101.addEventListener('animationstart',function () {animar=archi101;startanim();});
archi102.addEventListener('animationstart',function () {animar=archi102;startanim();});
archi103.addEventListener('animationstart',function () {animar=archi103;startanim();});
archi104.addEventListener('animationstart',function () {animar=archi104;startanim();});
archi105.addEventListener('animationstart',function () {animar=archi105;startanim();});
archi106.addEventListener('animationstart',function () {animar=archi106;startanim();});
archi107.addEventListener('animationstart',function () {animar=archi107;startanim();});
archi108.addEventListener('animationstart',function () {animar=archi108;startanim();});
archi109.addEventListener('animationstart',function () {animar=archi109;startanim();});
archi110.addEventListener('animationstart',function () {animar=archi110;startanim();});
archi111.addEventListener('animationstart',function () {animar=archi111;startanim();});
archi112.addEventListener('animationstart',function () {animar=archi112;startanim();});
archi113.addEventListener('animationstart',function () {animar=archi113;startanim();});
archi114.addEventListener('animationstart',function () {animar=archi114;startanim();});
archi115.addEventListener('animationstart',function () {animar=archi115;startanim();});
archi116.addEventListener('animationstart',function () {animar=archi116;startanim();});
archi117.addEventListener('animationstart',function () {animar=archi117;startanim();});
archi118.addEventListener('animationstart',function () {animar=archi118;startanim();});
archi119.addEventListener('animationstart',function () {animar=archi119;startanim();});
archi120.addEventListener('animationstart',function () {animar=archi120;startanim();});
archi121.addEventListener('animationstart',function () {animar=archi121;startanim();});
archi122.addEventListener('animationstart',function () {animar=archi122;startanim();});
archi123.addEventListener('animationstart',function () {animar=archi123;startanim();});
archi124.addEventListener('animationstart',function () {animar=archi124;startanim();});
archi125.addEventListener('animationstart',function () {animar=archi125;startanim();});
archi126.addEventListener('animationstart',function () {animar=archi126;startanim();});
archi127.addEventListener('animationstart',function () {animar=archi127;startanim();});
archi128.addEventListener('animationstart',function () {animar=archi128;startanim();});
archi129.addEventListener('animationstart',function () {animar=archi129;startanim();});
archi130.addEventListener('animationstart',function () {animar=archi130;startanim();});
archi131.addEventListener('animationstart',function () {animar=archi131;startanim();});
archi132.addEventListener('animationstart',function () {animar=archi132;startanim();});
archi133.addEventListener('animationstart',function () {animar=archi133;startanim();});
archi134.addEventListener('animationstart',function () {animar=archi134;startanim();});
archi135.addEventListener('animationstart',function () {animar=archi135;startanim();});
archi136.addEventListener('animationstart',function () {animar=archi136;startanim();});
archi137.addEventListener('animationstart',function () {animar=archi137;startanim();});
archi138.addEventListener('animationstart',function () {animar=archi138;startanim();});
archi139.addEventListener('animationstart',function () {animar=archi139;startanim();});
archi140.addEventListener('animationstart',function () {animar=archi140;startanim();});
archi141.addEventListener('animationstart',function () {animar=archi141;startanim();});
archi142.addEventListener('animationstart',function () {animar=archi142;startanim();});
archi143.addEventListener('animationstart',function () {animar=archi143;startanim();});
archi144.addEventListener('animationstart',function () {animar=archi144;startanim();});
archi145.addEventListener('animationstart',function () {animar=archi145;startanim();});
archi146.addEventListener('animationstart',function () {animar=archi146;startanim();});
archi147.addEventListener('animationstart',function () {animar=archi147;startanim();});
archi148.addEventListener('animationstart',function () {animar=archi148;startanim();});
archi149.addEventListener('animationstart',function () {animar=archi149;startanim();});
archi150.addEventListener('animationstart',function () {animar=archi150;startanim();});
archi151.addEventListener('animationstart',function () {animar=archi151;startanim();});
archi152.addEventListener('animationstart',function () {animar=archi152;startanim();});
archi153.addEventListener('animationstart',function () {animar=archi153;startanim();});
archi154.addEventListener('animationstart',function () {animar=archi154;startanim();});
archi155.addEventListener('animationstart',function () {animar=archi155;startanim();});
archi156.addEventListener('animationstart',function () {animar=archi156;startanim();});
archi157.addEventListener('animationstart',function () {animar=archi157;startanim();});
archi158.addEventListener('animationstart',function () {animar=archi158;startanim();});
archi159.addEventListener('animationstart',function () {animar=archi159;startanim();});
archi160.addEventListener('animationstart',function () {animar=archi160;startanim();});
archi161.addEventListener('animationstart',function () {animar=archi161;startanim();});
archi162.addEventListener('animationstart',function () {animar=archi162;startanim();});
archi163.addEventListener('animationstart',function () {animar=archi163;startanim();});
archi164.addEventListener('animationstart',function () {animar=archi164;startanim();});
archi165.addEventListener('animationstart',function () {animar=archi165;startanim();});
archi166.addEventListener('animationstart',function () {animar=archi166;startanim();});
archi167.addEventListener('animationstart',function () {animar=archi167;startanim();});
archi168.addEventListener('animationstart',function () {animar=archi168;startanim();});
archi169.addEventListener('animationstart',function () {animar=archi169;startanim();});
archi170.addEventListener('animationstart',function () {animar=archi170;startanim();});
archi171.addEventListener('animationstart',function () {animar=archi171;startanim();});
archi172.addEventListener('animationstart',function () {animar=archi172;startanim();});
archi173.addEventListener('animationstart',function () {animar=archi173;startanim();});
archi174.addEventListener('animationstart',function () {animar=archi174;startanim();});
archi175.addEventListener('animationstart',function () {animar=archi175;startanim();});
archi176.addEventListener('animationstart',function () {animar=archi176;startanim();});
archi177.addEventListener('animationstart',function () {animar=archi177;startanim();});
archi178.addEventListener('animationstart',function () {animar=archi178;startanim();});
archi179.addEventListener('animationstart',function () {animar=archi179;startanim();});
archi180.addEventListener('animationstart',function () {animar=archi180;startanim();});
archi181.addEventListener('animationstart',function () {animar=archi181;startanim();});
archi182.addEventListener('animationstart',function () {animar=archi182;startanim();});
archi183.addEventListener('animationstart',function () {animar=archi183;startanim();});
archi184.addEventListener('animationstart',function () {animar=archi184;startanim();});
archi185.addEventListener('animationstart',function () {animar=archi185;startanim();});
archi186.addEventListener('animationstart',function () {animar=archi186;startanim();});
archi187.addEventListener('animationstart',function () {animar=archi187;startanim();});
archi188.addEventListener('animationstart',function () {animar=archi188;startanim();});
archi189.addEventListener('animationstart',function () {animar=archi189;startanim();});
archi190.addEventListener('animationstart',function () {animar=archi190;startanim();});
archi191.addEventListener('animationstart',function () {animar=archi191;startanim();});
archi192.addEventListener('animationstart',function () {animar=archi192;startanim();});
archi193.addEventListener('animationstart',function () {animar=archi193;startanim();});
archi194.addEventListener('animationstart',function () {animar=archi194;startanim();});
archi195.addEventListener('animationstart',function () {animar=archi195;startanim();});
archi196.addEventListener('animationstart',function () {animar=archi196;startanim();});
archi197.addEventListener('animationstart',function () {animar=archi197;startanim();});
archi198.addEventListener('animationstart',function () {animar=archi198;startanim();});
archi199.addEventListener('animationstart',function () {animar=archi199;startanim();});
archi200.addEventListener('animationstart',function () {animar=archi200;startanim();});












